Lecture04　課題提出
sumo-yasu/20230823-RaiseTech-task pull request #3
Opened 2023-11-06 13:15 UTC by sumo-yasu

お世話になっております。
遅くなりましたが、第4回課題を作成しましたのでご確認よろしくお願いいたします。

あわせてRDS作成時のサブネットグループ設定について1点質問があります。今回サブネットグループとして2つのサブネットを追加しましたが（AZ：ap-northeast-1aとap-northeast-1cそれぞれに作成した各プライベートサブネット）、これは作成したRDS1台を2ケ所のプライベートサブネットに設置しているというイメージでよろしいでしょうか？　表現があっているか分からないのですが、作成したRDS1台を2つの場所に設置するイメージがピンとこなかったため気になりました。

2023-11-06 13:44 UTC, MasatoshiMizumoto requested changes
各値ソースのパラメータを書いてくださったのは素晴らしいです！
一方でスクショなど証跡が接続の画面しかないので、他の部分も頂きたいです！

2023-11-07 09:45 UTC, sumo-yasu commented
ご確認ありがとうございます。
ご指摘のあった通り　他の部分のスクショも添付しております。足りない部分等あれば、お手数ではございますが再度ご指摘をお願いいたします！！
<img width="931" alt="EC2 セキュリティグループ" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/91ddb2c3-f8c7-4d9f-8ec0-e1a512f67459">
<img width="938" alt="EC2 その1" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/5aef37e9-f495-4851-bd9c-f47a73806747">
<img width="937" alt="RDS サブネットグループ" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/19467e95-77fe-4fae-bf3c-9c0ba9f4b455">
<img width="936" alt="RDS セキュリティグループ" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/3e5bf108-a021-4bef-b27a-9dde24b4ad84">
<img width="935" alt="RDS その1" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/d655b23f-be04-45c2-8921-cd01c7026d6c">
<img width="938" alt="RDS その2" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/0ed4e48e-e693-4e98-b150-09456c72f04a">
<img width="934" alt="VPCパラメータ" src="https://github.com/sumo-yasu/20230823-RaiseTech-task/assets/110591513/389b3f9b-7b7d-4f5e-9b29-11bca3996ec0">

2023-11-08 03:25 UTC, sumo-yasu commented
お世話になっております。
指摘のあった箇所について修正しております。
ご確認よろしくお願いいたします。

2023-11-08 03:46 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-11-09 06:44 UTC, merged